# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "1w9193s10b0kd80ic36anim9svc34cvm0157w57ll30d4wsypdrv";
    x86_64-linux = "0ziy5k8jphfajrqmbyjdxpxk1m4a3x5l5lqnikpkxj963hb29lab";
    aarch64-linux = "05pz125nk2byd6jn1gh2jg067a0jvsdgx46azwd9yn8ijyf7fy7i";
    x86_64-darwin = "12yakhpq01lim680j73689f8hghr83m3rap5f35nja005qbgwksj";
    aarch64-darwin = "12yakhpq01lim680j73689f8hghr83m3rap5f35nja005qbgwksj";
  };

  urlMap = {
    i686-linux = "https://github.com/robinovitch61/wander/releases/download/v0.12.5/wander_0.12.5_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/robinovitch61/wander/releases/download/v0.12.5/wander_0.12.5_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/robinovitch61/wander/releases/download/v0.12.5/wander_0.12.5_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/robinovitch61/wander/releases/download/v0.12.5/wander_0.12.5_Darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/robinovitch61/wander/releases/download/v0.12.5/wander_0.12.5_Darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "wander";
  version = "0.12.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./wander $out/bin/wander
  '';

  system = system;

  meta = {
    description = "An efficient terminal application/TUI for interacting with your HashiCorp Nomad cluster.";
    homepage = "https://github.com/robinovitch61/wander";
    license = lib.licenses.MIT;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
