# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "07zzpv92m93vnl8x4k72hjnwl0b1ns9wy6b2lwk9xaxad5zfvpx7";
    x86_64-linux = "0x13q7b3zpk1z6jkbzj75v18g3csh3iavxa1ds93qhv156yxlkx7";
    aarch64-linux = "1i1ivyhbjsb3sdhsvy0qx6acmy0vxw799rwb6gn7iybsc9n0gypx";
    x86_64-darwin = "1m4i4h4yz9z9shhkmj9vvssgrrjpx5fr2h98pnrrb3d9rv7gazk8";
    aarch64-darwin = "1m4i4h4yz9z9shhkmj9vvssgrrjpx5fr2h98pnrrb3d9rv7gazk8";
  };

  urlMap = {
    i686-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.28.0/goreleaser-testing_0.28.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.28.0/goreleaser-testing_0.28.0_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.28.0/goreleaser-testing_0.28.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.28.0/goreleaser-testing_0.28.0_Darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.28.0/goreleaser-testing_0.28.0_Darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "goreleaser-testing";
  version = "0.28.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser-testing $out/bin/goreleaser-testing
  '';

  system = system;

  meta = {
    description = "Goreleaser testing description";
    homepage = "https://github.com/robinovitch61/goreleaser-testing";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
