# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "1g8xsmiq9blzarwby72z6cdz8s6pxwk2vb6qgvm26c28jcgbizwn";
    x86_64-linux = "0dzxh6jvz4cwg30mh3ggn4ar5ip26in12pfqwlk6wzgdb6n0igk2";
    aarch64-linux = "044g81ybpca7q6v1m89c7i89wz53paqkkrhzawnxm09q5mipid6w";
    x86_64-darwin = "0608cv2m7bbf3wws9v377pm8z8f17fjsyn363mr34ks5wbm88pay";
    aarch64-darwin = "0608cv2m7bbf3wws9v377pm8z8f17fjsyn363mr34ks5wbm88pay";
  };

  urlMap = {
    i686-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.20.0/goreleaser-testing_0.20.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.20.0/goreleaser-testing_0.20.0_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.20.0/goreleaser-testing_0.20.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.20.0/goreleaser-testing_0.20.0_Darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.20.0/goreleaser-testing_0.20.0_Darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "goreleaser-testing";
  version = "0.20.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser-testing $out/bin/goreleaser-testing
  '';

  system = system;

  meta = {
    description = "Goreleaser testing description";
    homepage = "https://github.com/robinovitch61/goreleaser-testing";
    license = lib.licenses.MIT;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
